### ISSUE TITLE
consider packages with universal Py3 wheels, Py3 tox configs or Py3 travis configs as Python 3 packages.

### ISSUE THREAD

**Issue by graingert** [cclauss/python3wos_asyncio#8]

**Comment by cclauss** [comment]
Hi @graingert ... Sorry for the lateness of the reply.  One of the goals here is to _simplify_ the process of automatically determining the Python 3 compatibility of PyPI packages.  I am trying to alert  package maintainers to the importance of properly specifying trove classifiers on PyPI.  I did do the work similar to what you suggested and used that info and the github API to issues to packages that had Python 3 support but no corresponding trove classifiers.  Some
maintainers liked it and made the updates and others complained about automated issue creation.
